# Generated by Django 5.2.8 on 2026-01-19 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.CharField(choices=[('Ladysmith', 'KwaZulu-Natal – Ladysmith'), ('Richards Bay', 'KwaZulu-Natal – Richards Bay'), ('Katlehong', 'Gauteng – Katlehong'), ('Vosloorus', 'Gauteng – Vosloorus')], default='Ladysmith', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_date',
            field=models.CharField(default='Ladysmith', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
