# Generated by Django 5.2.7 on 2026-01-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appointment_preferred_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='branch',
            field=models.CharField(choices=[('Ladysmith', 'KwaZulu-Natal – Ladysmith(Main Branch)'), ('Richards Bay', 'KwaZulu-Natal – Richards Bay'), ('Katlehong', 'Gauteng – Katlehong'), ('Vosloorus', 'Gauteng – Vosloorus')], max_length=50),
        ),
    ]
